export const PERMISSIONS: {[key: string]: Permissions } = {
    CALENDAR: EXPermissions.CALENDAR,
    CAMERA: EXPermissions.CAMERA,
    CONTACTS: EXPermissions.CONTACTS,
    LOCATION: EXPermissions.LOCATION,
    MICROPHONE: EXPermissions.AUDIO_RECORDING,
    CAMERA_ROLL: EXPermissions.CAMERA_ROLL,
    LOCAL_NOTIFICATIONS: EXPermissions.USER_FACING_NOTIFICATIONS,
    NOTIFICATIONS: EXPermissions.NOTIFICATIONS,
    SETTINGS: EXPermissions.SYSTEM_BRIGHTNESS,
};

export const DANGEROUS_PERMISSIONS: Permissions[] = [
    PERMISSIONS.CALENDAR,
    PERMISSIONS.CAMERA,
    PERMISSIONS.CONTACTS,
    PERMISSIONS.LOCATION,
    PERMISSIONS.AUDIO_RECORDING,
    PERMISSIONS.CAMERA_ROLL,
    PERMISSIONS.SYSTEM_BRIGHTNESS,
];